version: '3'

services:
  rag-chat:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
